version: '3'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - test-postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - test-bridge

  mq:
    image: rabbitmq:3.9-management-alpine
    hostname: test
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    volumes:
      - test-rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - test-bridge

networks:
  test-bridge:
    external: true

volumes:
  test-postgresql:
  test-rabbitmq:
